/*
 * This file is generated by jOOQ.
 */
package jooq.base.tables.records;


import javax.annotation.Generated;

import jooq.base.tables.Viewcardinfo;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewcardinfoRecord extends UpdatableRecordImpl<ViewcardinfoRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 1813818533;

    /**
     * Setter for <code>public.ViewCardInfo.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ViewCardInfo.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.ViewCardInfo.CARDALIACE</code>.
     */
    public void setCardaliace(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ViewCardInfo.CARDALIACE</code>.
     */
    public String getCardaliace() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.ViewCardInfo.DATA</code>.
     */
    public void setData(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.ViewCardInfo.DATA</code>.
     */
    public String getData() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Viewcardinfo.VIEWCARDINFO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Viewcardinfo.VIEWCARDINFO.CARDALIACE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Viewcardinfo.VIEWCARDINFO.DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCardaliace();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCardaliace();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewcardinfoRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewcardinfoRecord value2(String value) {
        setCardaliace(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewcardinfoRecord value3(String value) {
        setData(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewcardinfoRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewcardinfoRecord
     */
    public ViewcardinfoRecord() {
        super(Viewcardinfo.VIEWCARDINFO);
    }

    /**
     * Create a detached, initialised ViewcardinfoRecord
     */
    public ViewcardinfoRecord(Integer id, String cardaliace, String data) {
        super(Viewcardinfo.VIEWCARDINFO);

        set(0, id);
        set(1, cardaliace);
        set(2, data);
    }
}
