/*
 * This file is generated by jOOQ.
 */
package jooq.base;


import javax.annotation.Generated;

import jooq.base.tables.Clients;
import jooq.base.tables.Table_1;
import jooq.base.tables.records.ClientsRecord;
import jooq.base.tables.records.Table_1Record;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ClientsRecord> CLIENTS_PKEY = UniqueKeys0.CLIENTS_PKEY;
    public static final UniqueKey<Table_1Record> TABLE_1_PKEY = UniqueKeys0.TABLE_1_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ClientsRecord, Table_1Record> CLIENTS__CARD_ID = ForeignKeys0.CLIENTS__CARD_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<ClientsRecord> CLIENTS_PKEY = Internal.createUniqueKey(Clients.CLIENTS, "CLIENTS_pkey", Clients.CLIENTS.ID);
        public static final UniqueKey<Table_1Record> TABLE_1_PKEY = Internal.createUniqueKey(Table_1.TABLE_1, "TABLE_1_pkey", Table_1.TABLE_1.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<ClientsRecord, Table_1Record> CLIENTS__CARD_ID = Internal.createForeignKey(jooq.base.Keys.TABLE_1_PKEY, Clients.CLIENTS, "CLIENTS__card_id", Clients.CLIENTS.CARD_ID);
    }
}
