/*
 * This file is generated by jOOQ.
 */
package jooq.base;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.base.tables.Clients;
import jooq.base.tables.Viewcardinfo;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1848682238;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.CLIENTS</code>.
     */
    public final Clients CLIENTS = jooq.base.tables.Clients.CLIENTS;

    /**
     * The table <code>public.ViewCardInfo</code>.
     */
    public final Viewcardinfo VIEWCARDINFO = jooq.base.tables.Viewcardinfo.VIEWCARDINFO;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Clients.CLIENTS,
            Viewcardinfo.VIEWCARDINFO);
    }
}
