/*
 * This file is generated by jOOQ.
 */
package jooq.base;


import javax.annotation.Generated;

import jooq.base.tables.Clients;
import jooq.base.tables.Table_1;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.CLIENTS</code>.
     */
    public static final Clients CLIENTS = jooq.base.tables.Clients.CLIENTS;

    /**
     * The table <code>public.TABLE_1</code>.
     */
    public static final Table_1 TABLE_1 = jooq.base.tables.Table_1.TABLE_1;
}
